// Interface text in the three languages the app can show.
// Romaji mode is English except for mahjong terms. Yaku, winds, and round labels live in names.js.

const en = {
  loading: 'Loading…',
  saveFailed: 'This browser refused to save. Keep this page open and export or note the scores.',
  newGame: 'New game',
  inProgress: 'In progress',
  notExported: 'Not yet exported',
  export: 'Export data.json',
  exportHint: 'Commit the downloaded data.json to the repo. These games stay listed here until the new file is on the site.',
  pastGames: 'Past games',
  none: 'None yet.',

  date: 'Date',
  playerOptions: [[4, '4P'], [3, '3P']],
  lengthOptions: [['east', 'East Only'], ['south', 'East-South']],
  seats: 'Seats',
  namePlaceholder: 'Pick or type a name',
  points: 'Points',
  start: 'Start',
  return: 'Return',
  uma: 'Uma',
  umaFor: (place) => `Uma for ${place}`,
  oka: 'Oka',
  okaTo1st: (points) => `${points} to 1st`,
  rules: 'Rules',
  // Each switch label takes the return points, for the ones that mention them.
  switches: {
    kiriageMangan: () => 'Kiriage Mangan (7,700 rounds up to 8,000)',
    kazoeYakuman: () => 'Kazoe Yakuman (13+ han is yakuman; otherwise sanbaiman)',
    busting: () => 'Busting (Game ends below 0)',
    nagashiMangan: () => 'Nagashi Mangan',
    abortiveDraws: () => 'Abortive Draws (9 terminals, 4 winds, 4 riichi, 4 kans)',
    agariYame: () => 'Agari-yame (Dealer may end the game in the last round)',
    suddenDeath: (points) => `Sudden Death (continue play until someone reaches ${points})`,
  },
  notes: 'Notes',
  cancel: 'Cancel',
  startGame: 'Start game',
  needNames: 'Every seat needs a name.',
  sitOnce: 'Each player can only sit once.',
  umaZero: 'Uma must add up to 0.',
  needDate: 'Pick a date.',
  returnBelowStart: 'Return points can’t be below start points.',

  places: ['1st', '2nd', '3rd', '4th'],
  over: { normal: 'Game over', bust: 'Game over: bust', yame: 'Game over: dealer ended it', manual: 'Game ended early' },
  sticksTitle: 'Riichi sticks on the table',
  endsAtWarning: (round) => `The game should have ended after round ${round}. Fix or delete the rounds after it.`,
  yameBanner: 'The dealer may end the game here.',
  endGame: 'End game',
  gameNotFound: 'Game not found.',
  back: 'Back',
  allGames: '← All games',

  editing: (label) => `Editing ${label}`,
  outcomes: { ron: 'Ron', tsumo: 'Tsumo', draw: 'Draw', nagashi: 'Nagashi', abortive: 'Abortive', chombo: 'Chombo', other: 'Other' },
  winner: 'Winner',
  dealtIn: 'Fed',
  hanLabel: 'Han',
  fuLabel: 'Fu',
  needHanFu: 'Enter the han and fu.',
  badFu: 'That fu isn’t possible: 20, 25, or 30–110 in tens (1 han needs 30 or more).',
  yakuman: (n) => (n === 1 ? 'Yakuman' : `${n}x Yakuman`),
  limits: { Mangan: 'Mangan', Haneman: 'Haneman', Baiman: 'Baiman', Sanbaiman: 'Sanbaiman', 'Kazoe Yakuman': 'Kazoe Yakuman' },
  pao: 'Pao',
  noPao: 'None',
  tenpai: 'Tenpai',
  noten: 'Noten',
  chomboHint: 'Riichi sticks from this round are returned.',
  riichiMustBeTenpai: 'A player in riichi must be tenpai.',
  tapToWin: 'Tap the winner, or pick Draw or Other.',
  tapLoserOrTsumo: 'Tap who dealt in, or the winner again for tsumo.',
  abortiveKinds: { kyuushu: 'Nine Terminals', suufon: 'Four Winds', suucha: 'Four Riichi', suukaikan: 'Four Kans' },
  riichi: 'Riichi',
  tapTenpai: 'Tap the players in tenpai (nobody for all noten).',
  pickAbortive: 'Pick the kind of abortive draw.',
  suuchaNeedsRiichi: 'Four riichi needs every player marked riichi.',
  tapNagashi: 'Tap who got nagashi mangan.',
  tapChombo: 'Tap who made the chombo.',
  saveRound: 'Save round',
  saveChanges: 'Save changes',
  deleteRound: 'Delete round',
  tapToDeleteRound: 'Tap again to delete',

  tabs: { tiles: 'Tiles', hanFu: 'Han/Fu' },
  modes: { hand: 'Hand', chi: 'Chi', pon: 'Pon', kan: 'Kan', ankan: 'Closed Kan' },
  tapMore: (n) => `Tap ${n} more tile${n === 1 ? '' : 's'}.`,
  hanCount: (n) => `${n} han`,
  hanFu: (han, fu) => `${han} han ${fu} fu`,
  remove: 'Remove',
  handErrors: {
    tileCount: 'Tap in the rest of the hand.',
    needDora: 'Add the Dora indicator.',
    needUra: 'Add an Ura Dora indicator for each Dora indicator.',
    badChi: 'A chi must be 3 tiles in a row.',
    badPon: 'A pon must be 3 of the same tile.',
    badKan: 'A kan must be 4 of the same tile.',
    badMeld: 'Unknown meld.',
    tooMany: 'More than 4 of the same tile.',
    tooManyRed: 'More than 1 red five of the same suit.',
    removedIn3p: '2m–8m are not used in 3-player.',
    nukiIn4p: 'North Dora is only used in 3-player.',
    northSeat3p: 'There is no North seat in 3-player.',
    riichiAndDouble: 'Choose Riichi or Double Riichi, not both.',
    riichiOpen: 'Riichi needs a closed hand.',
    ippatsuNoRiichi: 'One Shot needs Riichi.',
    uraNoRiichi: 'Ura Dora needs Riichi.',
    haiteiRon: 'Last Tile Draw needs Tsumo.',
    houteiTsumo: 'Last Tile Discard needs Ron.',
    rinshanRon: 'After a Kan needs Tsumo.',
    rinshanNoKan: 'After a Kan needs a kan.',
    chankanTsumo: 'Robbing a Kan needs Ron.',
    tenhouChihouCalls: 'Blessing of Heaven and Earth need Tsumo with no calls.',
    tenhouNotDealer: 'Blessing of Heaven is only for the dealer.',
    chihouDealer: 'Blessing of Earth is only for non-dealers.',
    incomplete: 'Not a complete hand.',
    noYaku: 'No yaku.',
  },


  endNow: 'End game now',
  tapToEnd: 'Tap again to end now',
  resumeGame: 'Resume game',
  deleteGame: 'Delete game',
  tapToDeleteGame: 'Tap again to delete game',
};

const romaji = {
  ...en,
  lengthOptions: [['east', 'Tonpu'], ['south', 'Hanchan']],
  start: 'Genten',
  return: 'Kaeshi',
  switches: {
    kiriageMangan: () => 'Kiriage Mangan (7,700 rounds up to 8,000)',
    kazoeYakuman: () => 'Kazoe Yakuman (13+ Han is Yakuman; otherwise Sanbaiman)',
    busting: () => 'Tobi (Game ends below 0)',
    nagashiMangan: () => 'Nagashi Mangan',
    abortiveDraws: () => 'Tochuu Ryuukyoku (Kyuushu Kyuuhai, Suufon Renda, Suucha Riichi, Suukaikan)',
    agariYame: () => 'Agari-yame / Tenpai-yame (Oya may end the game in the last round)',
    suddenDeath: (points) => `Shaa-iri (continue play until someone reaches ${points})`,
  },
  over: { ...en.over, bust: 'Game over: Tobi' },
  yameBanner: 'Oya may end the game here (Agari-yame).',
  outcomes: { ...en.outcomes, draw: 'Ryuukyoku', nagashi: 'Nagashi Mangan', abortive: 'Tochuu Ryuukyoku' },
  dealtIn: 'Houjuu',
  needHanFu: 'Enter the Han and Fu.',
  badFu: 'That Fu isn’t possible: 20, 25, or 30–110 in tens (1 Han needs 30 or more).',
  yakuman: (n) => ['', 'Yakuman', 'Double Yakuman', 'Triple Yakuman'][n] ?? `${n}x Yakuman`,
  tapToWin: 'Tap the winner, or pick Ryuukyoku or Other.',
  tapLoserOrTsumo: 'Tap who dealt in, or the winner again for Tsumo.',
  abortiveKinds: { kyuushu: 'Kyuushu Kyuuhai', suufon: 'Suufon Renda', suucha: 'Suucha Riichi', suukaikan: 'Suukaikan' },
  tapTenpai: 'Tap the players in Tenpai (nobody for All Noten).',
  pickAbortive: 'Pick the kind of Tochuu Ryuukyoku.',
  suuchaNeedsRiichi: 'Suucha Riichi needs every player marked Riichi.',
  tapNagashi: 'Tap who got Nagashi Mangan.',
  hanCount: (n) => `${n} Han`,
  hanFu: (han, fu) => `${han} Han ${fu} Fu`,
  modes: { ...en.modes, ankan: 'Ankan' },
  handErrors: {
    ...en.handErrors,
    nukiIn4p: 'Nuki Dora is only used in 3-player.',
    ippatsuNoRiichi: 'Ippatsu needs Riichi.',
    haiteiRon: 'Haitei needs Tsumo.',
    houteiTsumo: 'Houtei needs Ron.',
    rinshanRon: 'Rinshan Kaihou needs Tsumo.',
    rinshanNoKan: 'Rinshan Kaihou needs a Kan.',
    chankanTsumo: 'Chankan needs Ron.',
    tenhouChihouCalls: 'Tenhou and Chihou need Tsumo with no calls.',
    tenhouNotDealer: 'Tenhou is only for the Oya.',
    chihouDealer: 'Chihou is only for non-dealers.',
    noYaku: 'No Yaku.',
  },
};

const jp = {
  loading: '読み込み中…',
  saveFailed: 'このブラウザに保存できませんでした。ページを閉じずに、書き出すか点数を控えてください。',
  newGame: '新規対局',
  inProgress: '対局中',
  notExported: '未反映',
  export: 'data.jsonを書き出す',
  exportHint: 'ダウンロードしたdata.jsonをリポジトリにコミットしてください。サイトに反映されるまで、ここに表示されます。',
  pastGames: '過去対局',
  none: 'なし',

  date: '日付',
  playerOptions: [[4, '四麻'], [3, '三麻']],
  lengthOptions: [['east', '東風'], ['south', '半荘']],
  seats: '席',
  namePlaceholder: '名前を選択または入力',
  points: '点数',
  start: '原点',
  return: '返し',
  uma: 'ウマ',
  umaFor: (place) => `${place}のウマ`,
  oka: 'オカ',
  okaTo1st: (points) => `1位に${points}`,
  rules: 'ルール',
  switches: {
    kiriageMangan: () => '切り上げ満貫（7700点を8000点に）',
    kazoeYakuman: () => '数え役満（13翻以上は役満、なしなら三倍満）',
    busting: () => 'トビあり（0点未満で終了）',
    nagashiMangan: () => '流し満貫',
    abortiveDraws: () => '途中流局（九種九牌・四風連打・四家立直・四開槓）',
    agariYame: () => 'アガリやめ・テンパイやめ（オーラスで親が終了できる）',
    suddenDeath: (points) => `西入（誰かが${points}点に達するまで続行）`,
  },
  notes: 'メモ',
  cancel: 'キャンセル',
  startGame: '対局開始',
  needNames: '全席に名前を入力してください',
  sitOnce: '同じプレイヤーは1席のみです',
  umaZero: 'ウマの合計を0にしてください',
  needDate: '日付を選んでください',
  returnBelowStart: '返しは原点以上にしてください',

  places: ['1位', '2位', '3位', '4位'],
  over: { normal: '対局終了', bust: '対局終了（トビ）', yame: '対局終了（アガリやめ）', manual: '途中終了' },
  sticksTitle: '供託',
  endsAtWarning: (round) => `第${round}局で対局は終了しているはずです。以降の局を修正または削除してください。`,
  yameBanner: '親はここで終了できます',
  endGame: '終了する',
  gameNotFound: '対局が見つかりません',
  back: '戻る',
  allGames: '← 対局一覧',

  editing: (label) => `${label}を編集中`,
  outcomes: { ron: 'ロン', tsumo: 'ツモ', draw: '流局', nagashi: '流し満貫', abortive: '途中流局', chombo: 'チョンボ', other: 'その他' },
  winner: '和了者',
  dealtIn: '放銃者',
  hanLabel: '翻',
  fuLabel: '符',
  needHanFu: '翻と符を入力してください',
  badFu: 'その符はありえません（20・25・30〜110の10刻み。1翻は30符以上）',
  yakuman: (n) => ['', '役満', 'ダブル役満', 'トリプル役満'][n] ?? `${n}倍役満`,
  limits: { Mangan: '満貫', Haneman: '跳満', Baiman: '倍満', Sanbaiman: '三倍満', 'Kazoe Yakuman': '数え役満' },
  pao: '責任払い',
  noPao: 'なし',
  tenpai: 'テンパイ',
  noten: 'ノーテン',
  chomboHint: '本局のリーチ棒は返却されます',
  riichiMustBeTenpai: 'リーチ者はテンパイである必要があります',
  tapToWin: '和了者をタップするか、流局・その他を選んでください',
  tapLoserOrTsumo: '放銃者をタップしてください（ツモならもう一度和了者をタップ）',
  abortiveKinds: { kyuushu: '九種九牌', suufon: '四風連打', suucha: '四家立直', suukaikan: '四開槓' },
  riichi: 'リーチ',
  tapTenpai: '聴牌の人をタップしてください（全員ノーテンならそのまま）',
  pickAbortive: '途中流局の種類を選んでください',
  suuchaNeedsRiichi: '四家立直は全員のリーチが必要です',
  tapNagashi: '流し満貫の人をタップしてください',
  tapChombo: 'チョンボした人をタップしてください',
  saveRound: '記録する',
  saveChanges: '変更を保存',
  deleteRound: '局を削除',
  tapToDeleteRound: 'もう一度タップで削除',

  tabs: { tiles: '牌', hanFu: '翻・符' },
  modes: { hand: '手牌', chi: 'チー', pon: 'ポン', kan: 'カン', ankan: '暗カン' },
  tapMore: (n) => `あと${n}枚`,
  hanCount: (n) => `${n}翻`,
  hanFu: (han, fu) => `${han}翻${fu}符`,
  remove: '削除',
  handErrors: {
    tileCount: '残りの牌を入力してください',
    needDora: 'ドラ表示牌を入力してください',
    needUra: '裏ドラ表示牌をドラと同じ枚数入力してください',
    badChi: 'チーは連続した3枚です',
    badPon: 'ポンは同じ牌3枚です',
    badKan: 'カンは同じ牌4枚です',
    badMeld: '不明な副露です',
    tooMany: '同じ牌が5枚以上あります',
    tooManyRed: '同じ種類の赤ドラが2枚以上あります',
    removedIn3p: '三麻では2萬〜8萬は使いません',
    nukiIn4p: '抜きドラは三麻のみです',
    northSeat3p: '三麻に北家はありません',
    riichiAndDouble: '立直とダブル立直はどちらか一方です',
    riichiOpen: '立直は門前のみです',
    ippatsuNoRiichi: '一発には立直が必要です',
    uraNoRiichi: '裏ドラには立直が必要です',
    haiteiRon: '海底はツモのみです',
    houteiTsumo: '河底はロンのみです',
    rinshanRon: '嶺上開花はツモのみです',
    rinshanNoKan: '嶺上開花にはカンが必要です',
    chankanTsumo: '槍槓はロンのみです',
    tenhouChihouCalls: '天和・地和は鳴きなしのツモのみです',
    tenhouNotDealer: '天和は親のみです',
    chihouDealer: '地和は子のみです',
    incomplete: '和了形になっていません',
    noYaku: '役がありません',
  },


  endNow: '今すぐ終了',
  tapToEnd: 'もう一度タップで終了',
  resumeGame: '対局を再開',
  deleteGame: '対局を削除',
  tapToDeleteGame: 'もう一度タップで対局を削除',
};

export const TEXT = { en, romaji, jp };

// A limit name from scoring.js ('Mangan', 'Yakuman', '2x Yakuman') in the given language.
export function limitText(limit, yakuman, t) {
  if (yakuman > 0) return t.yakuman(yakuman);
  return limit ? t.limits[limit] : null;
}
