// Interface text in the three languages the app can show.
// Romaji mode is English except for mahjong terms. Yaku, winds, and round labels live in names.js.

const en = {
  loading: 'Loading…',
  saveFailed: 'This browser refused to save. Keep this page open and export or note the scores.',
  newGame: 'New game',
  inProgress: 'In progress',
  notExported: 'Not yet exported',
  export: 'Export data.json',
  exportHint: 'Commit the downloaded data.json to the repo. These games stay listed here until the new file is on the site.',
  pastGames: 'Past games',
  none: 'None yet.',

  date: 'Date',
  playerOptions: [[4, '4P'], [3, '3P']],
  lengthOptions: [['east', 'East Only'], ['south', 'East-South']],
  seats: 'Seats',
  namePlaceholder: 'Pick or type a name',
  points: 'Points',
  start: 'Start',
  return: 'Return',
  uma: 'Uma',
  umaFor: (place) => `Uma for ${place}`,
  oka: 'Oka',
  okaTo1st: (points) => `${points} to 1st`,
  rules: 'Rules',
  switches: {
    kiriageMangan: 'Kiriage mangan',
    kazoeYakuman: 'Kazoe yakuman',
    busting: 'Busting (game ends below 0)',
    nagashiMangan: 'Nagashi mangan',
    abortiveDraws: 'Abortive draws',
  },
  notes: 'Notes',
  cancel: 'Cancel',
  startGame: 'Start game',
  needNames: 'Every seat needs a name.',
  sitOnce: 'Each player can only sit once.',
  umaZero: 'Uma must add up to 0.',
  needDate: 'Pick a date.',
  returnBelowStart: 'Return points can’t be below start points.',

  places: ['1st', '2nd', '3rd', '4th'],
  over: { normal: 'Game over', bust: 'Game over: bust', yame: 'Game over: dealer ended it', manual: 'Game ended early' },
  sticksTitle: 'Riichi sticks on the table',
  tileHint: 'Bottom of each tile: final points if the game ended now.',
  endsAtWarning: (round) => `The game should have ended after round ${round}. Fix or delete the rounds after it.`,
  yameBanner: 'The dealer may end the game here.',
  endGame: 'End game',
  gameNotFound: 'Game not found.',
  back: 'Back',
  allGames: '← All games',

  recordRound: 'Record round',
  editing: (label) => `Editing ${label}`,
  outcomes: { ron: 'Ron', tsumo: 'Tsumo', draw: 'Draw', nagashi: 'Nagashi', abortive: 'Abortive', chombo: 'Chombo' },
  winner: 'Winner',
  dealtIn: 'Dealt in',
  value: 'Value',
  hanAndFu: 'Han and fu',
  hanLabel: 'Han',
  han: (n) => `${n} han`,
  fu: (n) => `${n} fu`,
  yakuman: (n) => (n === 1 ? 'Yakuman' : `${n}x Yakuman`),
  limits: { Mangan: 'Mangan', Haneman: 'Haneman', Baiman: 'Baiman', Sanbaiman: 'Sanbaiman', 'Kazoe Yakuman': 'Kazoe Yakuman' },
  pao: 'Pao',
  noPao: 'None',
  paoFor: 'Pao for',
  tenpai: 'Tenpai',
  nagashiBy: 'Nagashi mangan by',
  chomboBy: 'Chombo by',
  chomboHint: 'Riichi sticks from this round are returned.',
  riichiThisRound: 'Riichi this round',
  pickWinner: 'Pick the winner.',
  pickLoser: 'Pick who dealt in.',
  pickNagashi: 'Pick who got nagashi mangan.',
  pickChombo: 'Pick who made the chombo.',
  riichiMustBeTenpai: 'A player in riichi must be tenpai.',
  saveRound: 'Save round',
  saveChanges: 'Save changes',
  deleteRound: 'Delete round',
  tapToDeleteRound: 'Tap again to delete',

  rounds: 'Rounds',
  edit: 'Edit',
  ronFrom: (winner, loser) => `${winner} ron from ${loser}`,
  tsumoBy: (winner) => `${winner} tsumo`,
  drawTenpai: (names) => `Draw · tenpai: ${names}`,
  drawAllNoten: 'Draw · all noten',
  nagashiRow: (name) => `Nagashi mangan · ${name}`,
  abortiveRow: 'Abortive draw',
  chomboRow: (name) => `Chombo · ${name}`,
  paoRow: (name) => `pao: ${name}`,
  riichiRow: (names) => `riichi: ${names}`,

  endNow: 'End game now',
  tapToEnd: 'Tap again to end now',
  resumeGame: 'Resume game',
  deleteGame: 'Delete game',
  tapToDeleteGame: 'Tap again to delete game',
};

const romaji = {
  ...en,
  lengthOptions: [['east', 'Tonpu'], ['south', 'Hanchan']],
  start: 'Genten',
  return: 'Kaeshi',
  switches: {
    kiriageMangan: 'Kiriage Mangan',
    kazoeYakuman: 'Kazoe Yakuman',
    busting: 'Tobi (game ends below 0)',
    nagashiMangan: 'Nagashi Mangan',
    abortiveDraws: 'Tochuu Ryuukyoku',
  },
  over: { ...en.over, bust: 'Game over: Tobi' },
  yameBanner: 'Oya may end the game here (Agari-yame).',
  outcomes: { ...en.outcomes, draw: 'Ryuukyoku', nagashi: 'Nagashi Mangan', abortive: 'Tochuu Ryuukyoku' },
  dealtIn: 'Houjuu',
  hanAndFu: 'Han / Fu',
  han: (n) => `${n} Han`,
  fu: (n) => `${n} Fu`,
  yakuman: (n) => ['', 'Yakuman', 'Double Yakuman', 'Triple Yakuman'][n] ?? `${n}x Yakuman`,
  nagashiBy: 'Nagashi Mangan by',
  drawTenpai: (names) => `Ryuukyoku · Tenpai: ${names}`,
  drawAllNoten: 'Ryuukyoku · All Noten',
  nagashiRow: (name) => `Nagashi Mangan · ${name}`,
  abortiveRow: 'Tochuu Ryuukyoku',
  paoRow: (name) => `Pao: ${name}`,
  riichiRow: (names) => `Riichi: ${names}`,
};

const jp = {
  loading: '読み込み中…',
  saveFailed: 'このブラウザに保存できませんでした。ページを閉じずに、書き出すか点数を控えてください。',
  newGame: '新規対局',
  inProgress: '対局中',
  notExported: '未反映',
  export: 'data.jsonを書き出す',
  exportHint: 'ダウンロードしたdata.jsonをリポジトリにコミットしてください。サイトに反映されるまで、ここに表示されます。',
  pastGames: '過去対局',
  none: 'なし',

  date: '日付',
  playerOptions: [[4, '四麻'], [3, '三麻']],
  lengthOptions: [['east', '東風'], ['south', '半荘']],
  seats: '席',
  namePlaceholder: '名前を選択または入力',
  points: '点数',
  start: '原点',
  return: '返し',
  uma: 'ウマ',
  umaFor: (place) => `${place}のウマ`,
  oka: 'オカ',
  okaTo1st: (points) => `1位に${points}`,
  rules: 'ルール',
  switches: {
    kiriageMangan: '切り上げ満貫',
    kazoeYakuman: '数え役満',
    busting: 'トビあり（0点未満で終了）',
    nagashiMangan: '流し満貫',
    abortiveDraws: '途中流局',
  },
  notes: 'メモ',
  cancel: 'キャンセル',
  startGame: '対局開始',
  needNames: '全席に名前を入力してください',
  sitOnce: '同じプレイヤーは1席のみです',
  umaZero: 'ウマの合計を0にしてください',
  needDate: '日付を選んでください',
  returnBelowStart: '返しは原点以上にしてください',

  places: ['1位', '2位', '3位', '4位'],
  over: { normal: '対局終了', bust: '対局終了（トビ）', yame: '対局終了（アガリやめ）', manual: '途中終了' },
  sticksTitle: '供託',
  tileHint: '各タイル下：今終了した場合の最終ポイント',
  endsAtWarning: (round) => `第${round}局で対局は終了しているはずです。以降の局を修正または削除してください。`,
  yameBanner: '親はここで終了できます',
  endGame: '終了する',
  gameNotFound: '対局が見つかりません',
  back: '戻る',
  allGames: '← 対局一覧',

  recordRound: '局の記録',
  editing: (label) => `${label}を編集中`,
  outcomes: { ron: 'ロン', tsumo: 'ツモ', draw: '流局', nagashi: '流し満貫', abortive: '途中流局', chombo: 'チョンボ' },
  winner: '和了者',
  dealtIn: '放銃者',
  value: '打点',
  hanAndFu: '翻・符',
  hanLabel: '翻',
  han: (n) => `${n}翻`,
  fu: (n) => `${n}符`,
  yakuman: (n) => ['', '役満', 'ダブル役満', 'トリプル役満'][n] ?? `${n}倍役満`,
  limits: { Mangan: '満貫', Haneman: '跳満', Baiman: '倍満', Sanbaiman: '三倍満', 'Kazoe Yakuman': '数え役満' },
  pao: '責任払い',
  noPao: 'なし',
  paoFor: '責任払いの対象',
  tenpai: '聴牌',
  nagashiBy: '流し満貫',
  chomboBy: 'チョンボ',
  chomboHint: '本局のリーチ棒は返却されます',
  riichiThisRound: '本局のリーチ',
  pickWinner: '和了者を選んでください',
  pickLoser: '放銃者を選んでください',
  pickNagashi: '流し満貫の人を選んでください',
  pickChombo: 'チョンボした人を選んでください',
  riichiMustBeTenpai: 'リーチ者はテンパイである必要があります',
  saveRound: '記録する',
  saveChanges: '変更を保存',
  deleteRound: '局を削除',
  tapToDeleteRound: 'もう一度タップで削除',

  rounds: '局の履歴',
  edit: '編集',
  ronFrom: (winner, loser) => `${winner} ロン（放銃：${loser}）`,
  tsumoBy: (winner) => `${winner} ツモ`,
  drawTenpai: (names) => `流局 · 聴牌：${names}`,
  drawAllNoten: '流局 · 全員ノーテン',
  nagashiRow: (name) => `流し満貫 · ${name}`,
  abortiveRow: '途中流局',
  chomboRow: (name) => `チョンボ · ${name}`,
  paoRow: (name) => `責任払い：${name}`,
  riichiRow: (names) => `リーチ：${names}`,

  endNow: '今すぐ終了',
  tapToEnd: 'もう一度タップで終了',
  resumeGame: '対局を再開',
  deleteGame: '対局を削除',
  tapToDeleteGame: 'もう一度タップで対局を削除',
};

export const TEXT = { en, romaji, jp };

// A limit name from scoring.js ('Mangan', 'Yakuman', '2x Yakuman') in the given language.
export function limitText(limit, yakuman, t) {
  if (yakuman > 0) return t.yakuman(yakuman);
  return limit ? t.limits[limit] : null;
}
